### ISSUE TITLE
function to skip the node 

### ISSUE THREAD

**Issue by ajopjo** [nurulc/incr-regex-package#3]
Hi: 

I'm looking at the package to do a reg ex search for the validity of a string.

I have a requirement in which a user enter a "*" to skip some of the nodes in the search.
As an example if my regex is 536X[5|8][A-Z]+ a user enters 5*5A.
So, is there any way I can search a character in the FSM node and if its not matching move to the next node and search. Help on this will be highly appreciated

**Comment by nurulc** [comment]
Hi,
Thanks for your interest. If I understand your requirement to be effectively convert the regexp to the following:
 You would like items that can be automatically filled in to be done and the user only need to input the values where there is a choice to make:
The following code might help:
var iRX = require('incr-regex-package');var { RXInputMask } = iRX;
// little helper functionfunction ins(rxi, str) {    for(var i=0; i<str.length; i++) { rxi.input(str.charAt(i)); }     return rxi; }
var im = new RXInputMask({pattern: "536X[5|8][A-Z]+"});
ins(im,"55A")assert(im.isDone() === 'OK')assert(im._getValue() === '536X5A')

Best Wishes Nurul 

    On Tuesday, May 26, 2020, 01:25:44 PM EDT, Ajo John <notifications@github.com> wrote:  
 
 


Hi:

I'm looking at the package to do a reg ex search for the validity of a string.

I have a requirement in which a user enter a "" to skip some of the nodes in the search.
As an example if my regex is 536X[5|8][A-Z]+ a user enters 55A.
So, is there any way I can search a character in the FSM node and if its not matching move to the next node and search. Help on this will be highly appreciated

**Comment by nurulc** [comment]
var iRX = require('incr-regex-package');
var { RXInputMask } = iRX;
// little helper function
function ins(rxi, str) {    for(var i=0; i<str.length; i++) { rxi.input(str.charAt(i)); }     return rxi; }
var im = new RXInputMask({pattern: "536X[5|8][A-Z]+"});
ins(im,"55A");
assert(im.isDone() === 'OK');
assert(im._getValue() === '536X5A');

**Comment by ajopjo** [comment]
Thank you @nurulc . have you incorporated apis to generate valid values from a regular expression, i saw that comment as part of the road map. Thanks!!

**Comment by nurulc** [comment]
The capability is a part of the package
